export const bardLevel1Spells = [
    {
      name: "Animal Friendship",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "24 hours",
      components: "V, S, M",
    },
    {
      name: "Bane",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
    {
      name: "Charm Person",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "1 hour",
      components: "V, S",
    },
    {
      name: "Color Spray",
      school: "Illusion",
      castingTime: "1 Action",
      range: "Self (15-foot cone)",
      duration: "1 round",
      components: "V, S, M",
    },
    {
      name: "Command",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "1 round",
      components: "V",
    },
    {
      name: "Comprehend Languages",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Cure Wounds",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Detect Magic",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 10 minutes",
      components: "V, S",
    },
    {
      name: "Disguise Self",
      school: "Illusion",
      castingTime: "1 Action",
      range: "Self",
      duration: "1 hour",
      components: "V, S",
    },
    {
      name: "Dissonant Whispers",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Distort Value",
      school: "Illusion",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "8 hours",
      components: "V",
    },
    {
      name: "Earth Tremor",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (10-foot radius)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Faerie Fire",
      school: "Evocation",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Concentration, up to 1 minute",
      components: "V",
    },
    {
      name: "Feather Fall",
      school: "Transmutation",
      castingTime: "1 Reaction",
      range: "60 feet",
      duration: "1 minute",
      components: "V, M",
    },
    {
      name: "Guiding Hand (UA)",
      school: "Divination",
      castingTime: "1 Minute",
      range: "5 feet",
      duration: "Concentration, up to 8 hours",
      components: "V, S",
    },
    {
      name: "Healing Word",
      school: "Evocation",
      castingTime: "1 Bonus Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Heroism",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "Touch",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Identify",
      school: "Divination",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Illusory Script",
      school: "Illusion",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "10 days",
      components: "S, M",
    },
    {
      name: "Longstrider",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Puppet (UA)",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Sense Emotion (UA)",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Silent Image",
      school: "Illusion",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Concentration, up to 10 minutes",
      components: "V, S, M",
    },
    {
      name: "Silvery Barbs",
      school: "Enchantment",
      castingTime: "1 Reaction",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Sleep",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "90 feet",
      duration: "1 minute",
      components: "V, S, M",
    },
    {
      name: "Speak with Animals",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "10 minutes",
      components: "V, S",
    },
    {
      name: "Sudden Awakening (UA)",
      school: "Enchantment",
      castingTime: "1 Bonus Action",
      range: "10 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Tasha's Hideous Laughter",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
    {
      name: "Thunderwave",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (15-foot cube)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Unearthly Chorus (UA)",
      school: "Illusion",
      castingTime: "1 Action",
      range: "Self (30-foot radius)",
      duration: "Concentration, up to 10 minutes",
      components: "V",
    },
    {
      name: "Unseen Servant",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "1 hour",
      components: "V, S, M",
    },
  ];

