export const bardCantrips = [
    {
      name: "Blade Ward",
      school: "Abjuration",
      castingTime: "1 Action",
      range: "Self",
      duration: "1 round",
      components: "V, S",
    },
    {
      name: "Dancing Lights",
      school: "Evocation",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
    {
      name: "Friends",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 1 minute",
      components: "S, M",
    },
    {
      name: "Light",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "1 hour",
      components: "V, M",
    },
    {
      name: "Mage Hand",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "1 minute",
      components: "V, S",
    },
    {
      name: "Mending",
      school: "Transmutation",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Message",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "1 round",
      components: "V, S, M",
    },
    {
      name: "Minor Illusion",
      school: "Illusion",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "1 minute",
      components: "S, M",
    },
    {
      name: "Prestidigitation",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "10 feet",
      duration: "Up to 1 hour",
      components: "V, S",
    },
    {
      name: "Thunderclap",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (5-foot radius)",
      duration: "Instantaneous",
      components: "S",
    },
    {
      name: "True Strike",
      school: "Divination",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Concentration, up to 1 round",
      components: "S",
    },
    {
      name: "Vicious Mockery",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V",
    },
  ];
