export const deities = [
    [
      "Auril, Goddess of Winter",
      "NE",
      "Nature, Tempest",
      "Six-pointed snowflake",
      "Lots of human sacrifices on icy altars, for evil and ice themed characters only.",
    ],
    [
      "Azuth, God of Wizards",
      "LN",
      "Arcana, Knowledge",
      "Left hand pointing upward outlined in fire",
      "Stereotypical old bearded wizard elevated to godhood, for characters who love them some wizarding.",
    ],
    [
      "Bane, God of Tyranny",
      "LE",
      "Order, War",
      "Upright black right hand, with thumb and fingers together",
      "Lord of being generically evil, think black knights and big evil churches.",
    ],
    [
      "Beshaba, Goddess of Misfortune",
      "CE",
      "Trickery",
      "Black antlers",
      "Think Jinx from “Teen Titans” elevated to godhood, loves bad luck and assassins.",
    ],
    [
      "Bhaal, God of Murder",
      "NE",
      "Death",
      "Skull surrounded by a ring of blood droplets",
      "Blood for the blood god, murder for the murder god. Bhaal just loves him some killing.",
    ],
    [
      "Chauntea, Goddess of Agriculture",
      "NG",
      "Life",
      "Sheaf of grain or a blooming rose over grain",
      "Cornucopias and good harvests, she's the obvious pick for former farmer characters.",
    ],
    [
      "Cyric, God of Lies",
      "CE",
      "Trickery",
      "White jawless skull on black or purple sunburst",
      "Mad god that successfully pissed off literally everybody, pick at your own risk, nobody is going to like you.",
    ],
    [
      "Deneir, God of Writing",
      "NG",
      "Knowledge",
      "Lit candle above an open eye",
      "Nerdier and weaker brother of Oghma, good for the nerdy underdog characters.",
    ],
    [
      "Eldath, Goddess of Peace",
      "NG",
      "Life, Nature",
      "Waterfall plunging into still pool",
      "Pacifist lake goddess of healing, good choice for healers and druids.",
    ],
    [
      "Gond, God of Craft",
      "N",
      "Forge, Knowledge",
      "Toothed cog with four spokes",
      "If your character's whole deal is making stuff, then Gond is a good bet.",
    ],
    [
      "Helm, God of Protection",
      "LN",
      "Life, Light, Protection",
      "Light Staring eye on upright left gauntlet",
      "Knight god who defends the weak, especially children.",
    ],
    [
      "Ilmater, God of Endurance",
      "LG",
      "Life, Protection",
      "Hands bound at the wrist with red cord",
      "Martyr god who's all about persevering for a better future, good for particularly selfless paladins.",
    ],
    [
      "Kelemvor, God of the Dead",
      "LN",
      "Grave, Death",
      "Upright skeletal arm holding balanced scales",
      "Somber but not evil, dutiful guard of the dead and bastion against undeath.",
    ],
    [
      "Lathander, God of Birth and Renewal",
      "NG",
      "Life, Light",
      "Light Road traveling into a sunrise",
      "The morninglord, pure chad energy, kind of vain but great for paladins and artists.",
    ],
    [
      "Leira, Goddess of Illusion",
      "CN",
      "Trickery",
      "Point-down triangle containing a swirl of mist",
      "She likes mists, masks and lies, not a bad option for sneaky characters.",
    ],
    [
      "Lliira, Goddess of Joy",
      "CG",
      "Life",
      "Triangle of three six-pointed stars",
      "Imagine if a “manic pixie dream girl” became a goddess. Fun bard pick.",
    ],
    [
      "Loviatar, Goddess of Pain",
      "LE",
      "Death",
      "Nine-tailed barbed scourge",
      "Quite literally the dominatrix goddess, super kinky.",
    ],
    [
      "Malar, God of the Hunt",
      "CE",
      "Nature",
      "Clawed paw",
      "One of the more tolerable evil gods, a good choice for evil druids.",
    ],
    [
      "Mask, God of Thieves",
      "CN",
      "Trickery",
      "Black mask",
      "If your edgelord rogue became a god he'd become Mask, and he's a genuinely still a good pick for edgelord rogues.",
    ],
    [
      "Mielikki, Goddess of Forests",
      "NG",
      "Nature",
      "Unicorn's head",
      "Think Artemis or any other “Huntress goddess” and you're right on the money, good for rangers.",
    ],
    [
      "Milil, God of Poetry and Song",
      "NG",
      "Light",
      "Five-stringed harp made of leaves",
      "The bard god of bards for bardic reasons who loves bards.",
    ],
    [
      "Myrkul, God of Death",
      "NE",
      "Death",
      "White human skull",
      "Death god in decidedly evil spooky skeleton flavor.",
    ],
    [
      "Mystra, Goddess of Magic",
      "NG",
      "Arcana, Knowledge",
      "Circle of seven stars, or nine stars encircling a flowing red mist, or a single star",
      "Magical lady devoted to keeping magic from getting out of hand and blowing everybody up.",
    ],
    [
      "Oghma, God of Knowledge",
      "N",
      "Knowledge",
      "Blank scroll",
      "God for bards who are about spreading stories and information rather than mischief.",
    ],
    [
      "Savras, god of Divination and Fate",
      "LN",
      "Knowledge",
      "Crystal ball containing many kinds of eyes",
      "Magic god who loves crystal balls and scrying, major occult mystery vibes.",
    ],
    [
      "Selûne, Goddess of the Moon",
      "CG",
      "Knowledge,  Life",
      "Pair of eyes surrounded by seven stars",
      "Goddess whose moods change with the phases of the moon, particularly honored by sailors.",
    ],
    [
      "Shar, Goddess of Darkness and Loss",
      "NE",
      "Death, Trickery",
      "Black disk encircled with a border",
      "Shadoweaver, knife lady who loves the dark, great for a character who hates the “good” gods.",
    ],
    [
      "Silvanus, God of Wild Nature",
      "N",
      "Nature",
      "Oak leaf",
      "I am Silvanus and I speak for the trees! Exclusive pick for druids and tree enthusiasts.",
    ],
    [
      "Sune, Goddess of Love and Beauty",
      "CG",
      "Life, Light",
      "Face of a beautiful red-haired woman",
      "Vanity personified, good for characters who want to embody thot energy.",
    ],
    [
      "Talona, Goddess of Disease and Poison",
      "CE",
      "Death",
      "Three teardrops on a triangle",
      "Loves making people sick and die, only right for characters who want to spread some plague.",
    ],
    [
      "Talos, God of Storms",
      "CE",
      "Tempest",
      "Three lightning bolts radiating from a central point",
      "Talos is basically a eviler Thor who loves wrecking up the place with storms.",
    ],
    [
      "Tempus, God of War",
      "N",
      "War",
      "Upright flaming sword",
      "Fights for the fight god, Tempus just loves fighting without any rhyme or reason.",
    ],
    [
      "Torm, God of Courage and Self-sacrifice",
      "LG",
      "Protection, War",
      "White right gauntlet",
      "Basically, the god of paladins, if you want a stereotypical paladin, this is your god.",
    ],
    [
      "Tymora, Goddess of Good Fortune",
      "CG",
      "Trickery",
      "Face-up coin",
      "Literally lady luck who favors the bold and the risk takers.",
    ],
    [
      "Tyr, God of Justice",
      "LG",
      "Order, Protection, War",
      "Balanced scales resting on a warhammer",
      "Literal Viking god of extremely lawful goodness, only for those characters committed to real lawful good.",
    ],
    [
      "Umberlee, Goddess of the Sea",
      "CE",
      "Tempest",
      "Wave curling left and right",
      "Called the bitch queen for a reason, spiteful sea witch perfect for both evil and sea themed characters.",
    ],
    [
      "Waukeen, Goddess of Trade",
      "N",
      "Knowledge, Trickery",
      "Upright coin with Waukeen's profile facing left",
      "The golden lady, an embodiment of laissez faire trade and a favorite of smugglers.",
    ],
  ];
