export const druidLevel1Spells = [
    {
      name: "Absorb Elements",
      school: "Abjuration",
      castingTime: "1 Reaction",
      range: "Self",
      duration: "1 round",
      components: "S",
    },
    {
      name: "Animal Friendship",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "24 hours",
      components: "V, S, M",
    },
    {
      name: "Beast Bond",
      school: "Divination",
      castingTime: "1 Action",
      range: "Touch",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
    {
      name: "Charm Person",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "1 hour",
      components: "V, S",
    },
    {
      name: "Create or Destroy Water",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Cure Wounds",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Detect Magic",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 10 minutes",
      components: "V, S",
    },
    {
      name: "Detect Poison and Disease",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 10 minutes",
      components: "V, S, M",
    },
    {
      name: "Earth Tremor",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (10-foot radius)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Entangle",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "90 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Faerie Fire",
      school: "Evocation",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Concentration, up to 1 minute",
      components: "V",
    },
    {
      name: "Fog Cloud",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "Concentration, up to 1 hour",
      components: "V, S",
    },
    {
      name: "Goodberry",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Guiding Hand (UA)",
      school: "Divination",
      castingTime: "1 Minute R",
      range: "5 feet",
      duration: "Concentration, up to 8 hours",
      components: "V, S",
    },
    {
      name: "Healing Word",
      school: "Evocation",
      castingTime: "1 Bonus Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Ice Knife",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "S, M",
    },
    {
      name: "Jump",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "1 minute",
      components: "V, S, M",
    },
    {
      name: "Longstrider",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Protection from Evil and Good",
      school: "Abjuration",
      castingTime: "1 Action",
      range: "Touch",
      duration: "Concentration, up to 10 minutes",
      components: "V, S, M",
    },
    {
      name: "Purify Food and Drink",
      school: "Transmutation",
      castingTime: "1 Action R",
      range: "10 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Snare",
      school: "Abjuration",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "Until dispelled or triggered",
      components: "V, S, M",
    },
    {
      name: "Speak with Animals",
      school: "Divination",
      castingTime: "1 Action R",
      range: "Self",
      duration: "10 minutes",
      components: "V, S",
    },
    {
      name: "Thunderwave",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (15-foot cube)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Wild Cunning (UA)",
      school: "Transmutation",
      castingTime: "1 Action R",
      range: "120 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
  ];
