export const druidCantrips = [
    {
      name: "Animal Shapes",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Concentration, up to 24 hours",
      components: "V, S",
    },
    {
      name: "Antipathy/Sympathy",
      school: "Enchantment",
      castingTime: "1 Hour",
      range: "60 feet",
      duration: "10 Days",
      components: "V, S, M",
    },
    {
      name: "Control Weather",
      school: "Transmutation",
      castingTime: "10 Minutes",
      range: "Self (5 mile radius)",
      duration: "Concentration, Up to 8 hours",
      components: "V, S, M",
    },
    {
      name: "Earthquake",
      school: "Evocation",
      castingTime: "1 Action",
      range: "500 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
    {
      name: "Feeblemind",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "150 feet",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Incendiary Cloud",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "150 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Sunburst",
      school: "Evocation",
      castingTime: "1 Action",
      range: "150 feet",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Tsunami",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "Sight",
      duration: "Concentration, up to 6 rounds",
      components: "V, S",
    },
  ];
