export const warlockCantrips = [
    {
      name: "Blade Ward",
      school: "Abjuration",
      castingTime: "1 Action",
      range: "Self",
      duration: "1 round",
      components: "V, S",
    },
    {
      name: "Booming Blade",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (5-foot radius)",
      duration: "1 round",
      components: "S, M",
    },
    {
      name: "Chill Touch",
      school: "Necromancy",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "1 round",
      components: "V, S",
    },
    {
      name: "Create Bonfire",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "60 Feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Eldritch Blast",
      school: "Evocation",
      castingTime: "1 Action",
      range: "120 Feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Friends",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 1 minute",
      components: "S, M",
    },
    {
      name: "Frostbite",
      school: "Evocation",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Green-Flame Blade",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (5-foot radius)",
      duration: "Instantaneous",
      components: "S, M",
    },
    {
      name: "Infestation",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Lightning Lure",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (15-foot radius)",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Mage Hand",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "1 minute",
      components: "V, S",
    },
    {
      name: "Magic Stone",
      school: "Transmutation",
      castingTime: "1 Bonus Action",
      range: "Touch",
      duration: "1 minute",
      components: "V, S",
    },
    {
      name: "Mind Sliver",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "1 round",
      components: "V",
    },
    {
      name: "Minor Illusion",
      school: "Illusion",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "1 minute",
      components: "S, M",
    },
    {
      name: "On/Off (UA)",
      school: "Transmutation T",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Poison Spray",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "10 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Prestidigitation",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "10 feet",
      duration: "Up to 1 hour",
      components: "V, S",
    },
    {
      name: "Sword Burst",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "Self (5-foot radius)",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Thunderclap",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (5-foot radius)",
      duration: "Instantaneous",
      components: "S",
    },
    {
      name: "Toll the Dead",
      school: "Necromancy",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "True Strike",
      school: "Divination",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Concentration, up to 1 round",
      components: "S",
    },
  ];

