export const warlockLevel1Spells = [
    {
      name: "Armor of Agathys",
      school: "Abjuration",
      castingTime: "1 Action",
      range: "Self",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Arms of Hadar",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "Self (10-foot radius)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Cause Fear",
      school: "Necromancy",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Charm Person",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "1 hour",
      components: "V, S",
    },
    {
      name: "Comprehend Languages",
      school: "Divination",
      castingTime: "1 Action R",
      range: "Self",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Distort Value",
      school: "Illusion",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "8 hours",
      components: "V",
    },
    {
      name: "Expeditious Retreat",
      school: "Transmutation",
      castingTime: "1 Bonus Action",
      range: "Self",
      duration: "Concentration, up to 10 minutes",
      components: "V, S",
    },
    {
      name: "Healing Elixir (UA)",
      school: "Conjuration",
      castingTime: "1 Minute",
      range: "Self",
      duration: "24 hours",
      components: "V, S, M",
    },
    {
      name: "Hellish Rebuke",
      school: "Evocation",
      castingTime: "1 Reaction",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Hex",
      school: "Enchantment",
      castingTime: "1 Bonus Action",
      range: "90 feet",
      duration: "Concentration, up to 1 hour",
      components: "V, S, M",
    },
    {
      name: "Id Insinuation (UA)",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Illusory Script",
      school: "Illusion",
      castingTime: "1 Minute R",
      range: "Touch",
      duration: "10 days",
      components: "S, M",
    },
    {
      name: "Infallible Relay (UA)",
      school: "Divination T",
      castingTime: "1 Minute",
      range: "Self",
      duration: "Concentration, up to 10 minutes",
      components: "V, S, M",
    },
    {
      name: "Protection from Evil and Good",
      school: "Abjuration",
      castingTime: "1 Action",
      range: "Touch",
      duration: "Concentration, up to 10 minutes",
      components: "V, S, M",
    },
    {
      name: "Puppet (UA)",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Remote Access (UA)",
      school: "Transmutation T",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "10 minutes",
      components: "V, S",
    },
    {
      name: "Sense Emotion (UA)",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Unseen Servant",
      school: "Conjuration",
      castingTime: "1 Action R",
      range: "60 feet",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Witch Bolt",
      school: "Evocation",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
  ];
