export const wizardCantrips = [
  {
    name: "Acid Splash",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 Feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Blade Ward",
    school: "Abjuration",
    castingTime: "1 Action",
    range: "Self",
    duration: "1 round",
    components: "V, S",
  },
  {
    name: "Booming Blade",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (5-foot radius)",
    duration: "1 round",
    components: "S, M",
  },
  {
    name: "Chill Touch",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "120 feet",
    duration: "1 round",
    components: "V, S",
  },
  {
    name: "Control Flames",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "60 Feet",
    duration: "Instantaneous or 1 hour",
    components: "S",
  },
  {
    name: "Create Bonfire",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "60 Feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S",
  },
  {
    name: "Dancing Lights",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 feet",
    duration: "Concentration up to 1 minute",
    components: "V, S, M",
  },
  {
    name: "Encode Thoughts",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "Self",
    duration: "8 hours",
    components: "S",
  },
  {
    name: "Fire Bolt",
    school: "Evocation",
    castingTime: "1 Action",
    range: "120 feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Friends",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "Self",
    duration: "Concentration, up to 1 minute",
    components: "S, M",
  },
  {
    name: "Frostbite",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Green-Flame Blade",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (5-foot radius)",
    duration: "Instantaneous",
    components: "S, M",
  },
  {
    name: "Gust",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Infestation",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "30 feet",
    duration: "Instantaneous",
    components: "V, S, M",
  },
  {
    name: "Light",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Touch",
    duration: "1 hour",
    components: "V, M",
  },
  {
    name: "Lightning Lure",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (15-foot radius)",
    duration: "Instantaneous",
    components: "V",
  },
  {
    name: "Mage Hand",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "30 feet",
    duration: "1 minute",
    components: "V, S",
  },
  {
    name: "Mending",
    school: "Transmutation",
    castingTime: "1 Minute",
    range: "Touch",
    duration: "Instantaneous",
    components: "V, S, M",
  },
  {
    name: "Message",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "120 feet",
    duration: "1 round",
    components: "V, S, M",
  },
  {
    name: "Mind Sliver",
    school: "Enchantment",
    castingTime: "1 Action",
    range: "60 feet",
    duration: "1 round",
    components: "V",
  },
  {
    name: "Minor Illusion",
    school: "Illusion",
    castingTime: "1 Action",
    range: "30 feet",
    duration: "1 minute",
    components: "S, M",
  },
  {
    name: "Mold Earth",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 feet",
    duration: "Instantaneous or 1 hour",
    components: "S",
  },
  {
    name: "On/Off (UA)",
    school: "Transmutation T",
    castingTime: "1 Action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Poison Spray",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "10 feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Prestidigitation",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "10 feet",
    duration: "Up to 1 hour",
    components: "V, S",
  },
  {
    name: "Ray of Frost",
    school: "Evocation",
    castingTime: "1 Action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Sapping Sting",
    school: "Necromancy D",
    castingTime: "1 Action",
    range: "30 feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Shape Water",
    school: "Transmutation",
    castingTime: "1 Action",
    range: "30 feet",
    duration: "Instantaneous or 1 hour",
    components: "S",
  },
  {
    name: "Shocking Grasp",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Touch",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "Sword Burst",
    school: "Conjuration",
    castingTime: "1 Action",
    range: "Self (5-foot radius)",
    duration: "Instantaneous",
    components: "V",
  },
  {
    name: "Thunderclap",
    school: "Evocation",
    castingTime: "1 Action",
    range: "Self (5-foot radius)",
    duration: "Instantaneous",
    components: "S",
  },
  {
    name: "Toll the Dead",
    school: "Necromancy",
    castingTime: "1 Action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S",
  },
  {
    name: "True Strike",
    school: "Divination",
    castingTime: "1 Action",
    range: "30 feet",
    duration: "Concentration up to 1 round",
    components: "S",
  },
];
