export const wizardLevel1Spells = [
    {
      name: "Absorb Elements",
      school: "Abjuration",
      castingTime: "1 Reaction",
      range: "Self",
      duration: "1 round",
      components: "S",
    },
    {
      name: "Acid Stream (UA)",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (30-foot line)",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
    {
      name: "Alarm",
      school: "Abjuration",
      castingTime: "1 Minute",
      range: "30 feet",
      duration: "8 Hours",
      components: "V, S, M",
    },
    {
      name: "Burning Hands",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (15-foot cone)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Catapult",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "S",
    },
    {
      name: "Cause Fear",
      school: "Necromancy",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Charm Person",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "1 hour",
      components: "V, S",
    },
    {
      name: "Chromatic Orb",
      school: "Evocation",
      castingTime: "1 Action",
      range: "90 feet",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Color Spray",
      school: "Illusion",
      castingTime: "1 Action",
      range: "Self (15-foot cone)",
      duration: "1 round",
      components: "V, S, M",
    },
    {
      name: "Comprehend Languages",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Detect Magic",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 10 minutes",
      components: "V, S",
    },
    {
      name: "Disguise Self",
      school: "Illusion",
      castingTime: "1 Action",
      range: "Self",
      duration: "1 hour",
      components: "V, S",
    },
    {
      name: "Distort Value",
      school: "Illusion",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "8 hours",
      components: "V",
    },
    {
      name: "Earth Tremor",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (10-foot radius)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Expeditious Retreat",
      school: "Transmutation",
      castingTime: "1 Bonus Action",
      range: "Self",
      duration: "Concentration, up to 10 minutes",
      components: "V, S",
    },
    {
      name: "False Life",
      school: "Necromancy",
      castingTime: "1 Action",
      range: "Self",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Feather Fall",
      school: "Transmutation",
      castingTime: "1 Reaction",
      range: "60 feet",
      duration: "1 minute",
      components: "V, M",
    },
    {
      name: "Find Familiar",
      school: "Conjuration",
      castingTime: "1 Hour",
      range: "10 feet",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Fog Cloud",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "Concentration, up to 1 hour",
      components: "V, S",
    },
    {
      name: "Frost Fingers",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (15-foot cone)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Gift of Alacrity",
      school: "Divination DC",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "8 hours",
      components: "V, S",
    },
    {
      name: "Grease",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "1 minute",
      components: "V, S, M",
    },
    {
      name: "Guiding Hand (UA)",
      school: "Divination",
      castingTime: "1 Minute R",
      range: "5 feet",
      duration: "Concentration, up to 8 hours",
      components: "V, S",
    },
    {
      name: "Healing Elixir (UA)",
      school: "Conjuration",
      castingTime: "1 Minute",
      range: "Self",
      duration: "24 hours",
      components: "V, S, M",
    },
    {
      name: "Ice Knife",
      school: "Conjuration",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "S, M",
    },
    {
      name: "Id Insinuation (UA)",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Identify",
      school: "Divination",
      castingTime: "1 Minute R",
      range: "Touch",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Illusory Script",
      school: "Illusion",
      castingTime: "1 Minute R",
      range: "Touch",
      duration: "10 days",
      components: "S, M",
    },
    {
      name: "Infallible Relay (UA)",
      school: "Divination T",
      castingTime: "1 Minute",
      range: "Self",
      duration: "Concentration, up to 10 minutes",
      components: "V, S, M",
    },
    {
      name: "Jim's Magic Missile",
      school: "Evocation",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "Instantaneous",
      components: "V, S, M",
    },
    {
      name: "Jump",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "1 minute",
      components: "V, S, M",
    },
    {
      name: "Longstrider",
      school: "Transmutation",
      castingTime: "1 Action",
      range: "Touch",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Mage Armor",
      school: "Abjuration",
      castingTime: "1 Action",
      range: "Touch",
      duration: "8 hours",
      components: "V, S, M",
    },
    {
      name: "Magic Missile",
      school: "Evocation",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Magnify Gravity",
      school: "Transmutation DG",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "1 round",
      components: "V, S",
    },
    {
      name: "Protection from Evil and Good",
      school: "Abjuration",
      castingTime: "1 Action",
      range: "Touch",
      duration: "Concentration, up to 10 minutes",
      components: "V, S, M",
    },
    {
      name: "Puppet (UA)",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Ray of Sickness",
      school: "Necromancy",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Remote Access (UA)",
      school: "Transmutation T",
      castingTime: "1 Action",
      range: "120 feet",
      duration: "10 minutes",
      components: "V, S",
    },
    {
      name: "Sense Emotion (UA)",
      school: "Divination",
      castingTime: "1 Action",
      range: "Self",
      duration: "Concentration, up to 1 minute",
      components: "V, S",
    },
    {
      name: "Shield",
      school: "Abjuration",
      castingTime: "1 Reaction",
      range: "Self",
      duration: "1 round",
      components: "V, S",
    },
    {
      name: "Silent Image",
      school: "Illusion",
      castingTime: "1 Action",
      range: "60 feet",
      duration: "Concentration, up to 10 minutes",
      components: "V, S, M",
    },
    {
      name: "Silvery Barbs",
      school: "Enchantment",
      castingTime: "1 Reaction",
      range: "60 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Sleep",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "90 feet",
      duration: "1 minute",
      components: "V, S, M",
    },
    {
      name: "Snare",
      school: "Abjuration",
      castingTime: "1 Minute",
      range: "Touch",
      duration: "Until dispelled or triggered",
      components: "V, S, M",
    },
    {
      name: "Sudden Awakening (UA)",
      school: "Enchantment",
      castingTime: "1 Bonus Action",
      range: "10 feet",
      duration: "Instantaneous",
      components: "V",
    },
    {
      name: "Tasha's Caustic Brew",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (30-foot line)",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
    {
      name: "Tasha's Hideous Laughter",
      school: "Enchantment",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
    {
      name: "Tenser's Floating Disk",
      school: "Conjuration",
      castingTime: "1 Action R",
      range: "30 feet",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Thunderwave",
      school: "Evocation",
      castingTime: "1 Action",
      range: "Self (15-foot cube)",
      duration: "Instantaneous",
      components: "V, S",
    },
    {
      name: "Unseen Servant",
      school: "Conjuration",
      castingTime: "1 Action R",
      range: "60 feet",
      duration: "1 hour",
      components: "V, S, M",
    },
    {
      name: "Witch Bolt",
      school: "Evocation",
      castingTime: "1 Action",
      range: "30 feet",
      duration: "Concentration, up to 1 minute",
      components: "V, S, M",
    },
  ];
