from app.models import db, Character, environment, SCHEMA
from sqlalchemy.sql import text


# Adds a demo user, you can add other users here if you want
def seed_users():
    characters = [
        Character(
            user_id=None,
            level=7,
            name='Lyra Dawnflower',
            role='Rogue',
            race='Half-Elf',
            max_hp=48,
            current_hp=34,
            strength=12,
            dexterity=18,
            constitution=14,
            intelligence=16,
            wisdom=10,
            charisma=16,
            armor=['Leather Armor', 'Cloak of Elvenkind'],
            equipped=['Rapier'],
            inventory=['Shortbow', 'Dagger', 'Crossbow', 'Thieves\' Tools', 'Potion of Invisibility'],
            languages=['Common', 'Elvish', 'Thieves\' Cant'],
            spells=[],
            tools=[],
            weapons=['Rapier', 'Shortbow', 'Dagger', 'Crossbow'],
            initiative=6,
            armor_class=15,
            vision='darkvision',
            acrobatics=8,
            animal_handling=0,
            arcana=0,
            athletics=5,
            deception=10,
            history=0,
            insight=0,
            intimidation=5,
            investigation=0,
            medicine=0,
            nature=0,
            perception=6,
            performance=0,
            persuasion=10,
            religion=0,
            sleight_of_hand=10,
            stealth=12,
            survival=0,
            alignment='Chaotic Good',
            appearance='Graceful and nimble, with silver hair and bright blue eyes.',
            background='A skilled thief and expert in stealth and deception. Lyra Dawnflower is a valiant and noble paladin, devoted to the service of the god Bahamut. She was raised in the sacred city of Celestia, where she trained as a holy warrior from a young age. Her demeanor is calm and composed, but she is unyielding in her pursuit of justice and protection for the innocent. Lyra\'s goals are to rid the world of evil and corruption, and to bring hope and healing to those in need. As a devout follower of Bahamut, she is guided by a strong sense of duty and honor, and she believes in the power of redemption and second chances.',
            img_url='https://i.imgur.com/WqrFsPl.jpg',
            faith='Bahamut'
        ),
            Character(
            user_id=None,
            level=5,
            name='Eldric Shadowcaster',
            role='Wizard',
            race='Human',
            max_hp=32,
            current_hp=32,
            strength=10,
            dexterity=14,
            constitution=12,
            intelligence=18,
            wisdom=13,
            charisma=10,
            armor=['Robes of Protection'],
            equipped=['Staff of the Arcane'],
            inventory=['Spellbook', 'Potion of Healing', 'Wand of Magic Missiles'],
            languages=['Common', 'Draconic', 'Infernal'],
            spells=['Mage Armor', 'Fireball', 'Magic Missile', 'Counterspell', 'Detect Magic', 'Feather Fall'],
            tools=['Arcane Focus'],
            weapons=['Dagger'],
            initiative=2,
            armor_class=12,
            acrobatics=2,
            animal_handling=0,
            arcana=8,
            athletics=0,
            deception=0,
            history=4,
            insight=3,
            intimidation=0,
            investigation=6,
            medicine=0,
            nature=4,
            perception=3,
            performance=0,
            persuasion=0,
            religion=0,
            sleight_of_hand=0,
            stealth=2,
            survival=0,
            alignment='Neutral Good',
            appearance='Tall and thin, with dark hair and piercing green eyes.',
            background="""A powerful wizard and scholar, Eldric Shadowcaster spends much of his time studying ancient tomes and deciphering magical secrets. He has a reserved and contemplative demeanor, preferring solitude over crowds. Eldric's ultimate goal is to unravel the mysteries of the arcane and become a renowned archmage. He seeks knowledge and understanding above all else, and he values wisdom and intellect. While not overly social, he forms strong bonds with those he considers true friends. Eldric is known for his expertise in fire-based spells and his talent for countering enemy magic. He has a deep fascination with dragons and their history, often spending hours delving into ancient dragon lore. Eldric reveres Mystra, the goddess of magic, and seeks her guidance in his quest for magical mastery.""",
            img_url='https://example.com/eldric_shadowcaster.jpg',
            faith='Mystra'
        ),
        Character(
            user_id=None,
            level=5,
            name='Eldric Shadowcaster',
            role='Wizard',
            race='Human',
            max_hp=32,
            current_hp=32,
            strength=10,
            dexterity=14,
            constitution=12,
            intelligence=18,
            wisdom=13,
            charisma=10,
            armor=['Robes of Protection'],
            equipped=['Staff of the Arcane'],
            inventory=['Spellbook', 'Potion of Healing', 'Wand of Magic Missiles'],
            languages=['Common', 'Draconic', 'Infernal'],
            spells=['Mage Armor', 'Fireball', 'Magic Missile', 'Counterspell', 'Detect Magic', 'Feather Fall'],
            tools=['Arcane Focus'],
            weapons=['Dagger'],
            initiative=2,
            armor_class=12,
            vision='normal',
            acrobatics=2,
            animal_handling=0,
            arcana=8,
            athletics=0,
            deception=0,
            history=4,
            insight=3,
            intimidation=0,
            investigation=6,
            medicine=0,
            nature=4,
            perception=3,
            performance=0,
            persuasion=0,
            religion=0,
            sleight_of_hand=0,
            stealth=2,
            survival=0,
            alignment='Neutral Good',
            appearance='Tall and thin, with dark hair and piercing green eyes.',
            background="""A powerful wizard and scholar, Eldric Shadowcaster spends much of his time studying ancient tomes and deciphering magical secrets. He has a reserved and contemplative demeanor, preferring solitude over crowds. Eldric's ultimate goal is to unravel the mysteries of the arcane and become a renowned archmage. He seeks knowledge and understanding above all else, and he values wisdom and intellect. While not overly social, he forms strong bonds with those he considers true friends. Eldric is known for his expertise in fire-based spells and his talent for countering enemy magic. He has a deep fascination with dragons and their history, often spending hours delving into ancient dragon lore. Eldric reveres Mystra, the goddess of magic, and seeks her guidance in his quest for magical mastery.""",
            img_url='https://i.imgur.com/ZHCXW3k.jpg',
            faith='Mystra'
        ),
        Character(
            user_id=None,
            level=6,
            name='Astrid Stormblade',
            role='Barbarian',
            race='Half-Orc',
            max_hp=68,
            current_hp=68,
            strength=20,
            dexterity=14,
            constitution=18,
            intelligence=8,
            wisdom=12,
            charisma=10,
            armor=['Hide Armor'],
            equipped=['Greataxe'],
            inventory=['Javelin', 'Potion of Healing', 'Rage Elixir'],
            languages=['Common', 'Orcish'],
            spells=[],
            tools=[],
            weapons=['Greataxe', 'Javelin'],
            initiative=2,
            armor_class=14,
            vision='darkvision',
            acrobatics=2,
            animal_handling=0,
            arcana=0,
            athletics=9,
            deception=0,
            history=0,
            insight=1,
            intimidation=5,
            investigation=0,
            medicine=1,
            nature=0,
            perception=1,
            performance=0,
            persuasion=0,
            religion=0,
            sleight_of_hand=0,
            stealth=2,
            survival=1,
            alignment='Chaotic Neutral',
            appearance='Towering and muscular, with greenish skin and a long, tusked underbite.',
            background="""A fierce warrior with a volatile temper, Astrid Stormblade is a Half-Orc barbarian known for her brute strength and unwavering determination. Raised among her orcish kin, she eventually ventured into the world to find her own path. Astrid's demeanor is often intimidating, but she is fiercely loyal to those she considers her allies. Her ultimate goal is to seek the thrill of battle and prove her worth in combat. She believes in survival of the fittest and embraces her primal instincts in battle, unleashing her rage when confronting foes. Although she may seem aggressive, she has a soft spot for nature and can display moments of unexpected kindness. Astrid worships Gruumsh, the chaotic evil god of orcs, as she sees strength as the true measure of one's worth.""",
            img_url='https://i.imgur.com/2BgMDJm.jpg',
            faith='Gruumsh'
        ),
            Character(
            user_id=None,
            level=5,
            name='Elara Nightshade',
            role='Wizard',
            race='Elf',
            max_hp=28,
            current_hp=28,
            strength=8,
            dexterity=16,
            constitution=12,
            intelligence=20,
            wisdom=10,
            charisma=14,
            armor=['Mage Armor'],
            equipped=['Staff of the Magi'],
            inventory=['Spellbook', 'Potion of Intelligence', 'Scroll of Fireball'],
            languages=['Common', 'Elvish'],
            spells=['Fireball', 'Magic Missile', 'Shield', 'Invisibility', 'Feather Fall', 'Detect Magic'],
            tools=['Herbalism Kit'],
            weapons=[],
            initiative=3,
            armor_class=13,
            vision='darkvision',
            acrobatics=3,
            animal_handling=0,
            arcana=9,
            athletics=0,
            deception=2,
            history=6,
            insight=2,
            intimidation=2,
            investigation=6,
            medicine=2,
            nature=2,
            perception=2,
            performance=2,
            persuasion=2,
            religion=2,
            sleight_of_hand=3,
            stealth=3,
            survival=2,
            alignment='Lawful Good',
            appearance='Tall and slender, with long silver hair and piercing blue eyes.',
            background="""Elara Nightshade is an Elf wizard known for her vast knowledge of arcane magic. As an avid scholar, she spends much of her time studying ancient tomes and learning new spells. She has a calm and composed demeanor, often taking a methodical approach to problem-solving. Elara values wisdom and knowledge and is always eager to uncover the mysteries of the world. While she prefers peaceful solutions, she can be formidable in battle when her friends or her principles are threatened. Her trusty staff, the Staff of the Magi, aids her in channeling powerful spells. Elara's ultimate goal is to safeguard ancient magical artifacts and protect the world from the misuse of arcane powers. She follows Corellon Larethian, the god of elves and the patron of arcane magic, whom she reveres for his guidance and wisdom.""",
            img_url='https://i.imgur.com/3InkcNF.jpg',
            faith='Corellon Larethian'
        ),
        Character(
            user_id=None,
            level=5,
            name='Isabella Nightshade',
            role='Paladin',
            race='Tiefling',
            max_hp=45,
            current_hp=45,
            strength=16,
            dexterity=10,
            constitution=14,
            intelligence=12,
            wisdom=12,
            charisma=18,
            armor=['Plate Armor', 'Shield'],
            equipped=['Longsword', 'Holy Symbol'],
            inventory=['Handaxe', 'Healing Potion', 'Scroll of Protection from Evil and Good'],
            languages=['Common', 'Infernal'],
            spells=['Bless', 'Cure Wounds', 'Searing Smite'],
            tools=[],
            weapons=['Longsword', 'Handaxe'],
            initiative=0,
            armor_class=20,
            acrobatics=0,
            animal_handling=1,
            arcana=1,
            athletics=3,
            deception=4,
            history=1,
            insight=3,
            intimidation=4,
            investigation=1,
            medicine=3,
            nature=1,
            perception=3,
            performance=4,
            persuasion=6,
            religion=3,
            sleight_of_hand=0,
            stealth=0,
            survival=1,
            alignment='Lawful Good',
            appearance='With crimson skin, horns, and glowing yellow eyes, Isabella has the distinct features of a tiefling. Despite her appearance, her radiant smile and warm personality put others at ease.',
            background="""Isabella Nightshade, a tiefling paladin, is a beacon of hope in a world shrouded in darkness. Born into a family of tieflings, she has faced prejudice and mistrust from those who fear her infernal heritage. But Isabella has chosen a different path, one of righteousness and compassion. She became a paladin to prove that goodness knows no race or lineage. Her devotion to her oath and her faith grants her divine powers that she uses to protect the innocent and smite evil. Isabella's strong sense of justice drives her to right the wrongs of the world and bring hope to the oppressed. She carries a longsword and a holy symbol, using both to channel her divine powers in battle. With her radiant smile and warm personality, Isabella seeks to inspire others to follow the path of goodness and redemption.""",
            img_url='https://i.imgur.com/nHTKZ9C.jpg',
            faith='Torm, the Loyal Fury'
        ),
        Character(
            user_id=None,
            level=6,
            name="Aurelius Flameheart",
            role="Fighter",
            race="Dragonborn",
            max_hp=60,
            current_hp=60,
            strength=20,
            dexterity=14,
            constitution=18,
            intelligence=8,
            wisdom=12,
            charisma=10,
            armor=["Half Plate Armor"],
            equipped=["Greataxe"],
            inventory=["Javelin", "Potion of Healing"],
            languages=["Common", "Draconic"],
            spells=[],
            tools=["Smith's Tools"],
            weapons=["Greataxe", "Javelin"],
            initiative=2,
            armor_class=16,
            vision='normal',
            acrobatics=2,
            animal_handling=1,
            arcana=0,
            athletics=8,
            deception=0,
            history=0,
            insight=1,
            intimidation=3,
            investigation=0,
            medicine=1,
            nature=0,
            perception=1,
            performance=0,
            persuasion=0,
            religion=0,
            sleight_of_hand=2,
            stealth=2,
            survival=1,
            alignment="Chaotic Neutral",
            appearance="""Aurelius Flameheart stands tall with his
                           gleaming bronze scales and fiery orange eyes.
                           His presence is both commanding and inspiring.""",
            background="""Aurelius Flameheart, the last of the Flameheart
                           lineage, is a Dragonborn with an indomitable
                           spirit and an unyielding determination. Raised
                           by his elders in the secluded Emberclaw tribe,
                           Aurelius was chosen by the flames of their ancient
                           totem as a bearer of the eternal fire. Gifted with
                           the power of fire manipulation, he wields the
                           element of flames to protect his kin and vanquish
                           his foes. Aurelius carries the heavy burden of
                           safeguarding his tribe's ancient traditions and
                           carrying the legacy of his ancestors. Beyond the
                           battlefield, Aurelius is a skilled blacksmith,
                           forging weapons of extraordinary power for his
                           brethren. Despite his fierce demeanor in battle,
                           Aurelius possesses a compassionate heart and is
                           deeply devoted to the well-being of his tribe.
                           His journey will lead him through trials and
                           revelations, uncovering the secrets of his clan's
                           past and forging a new path for the future of
                           Dragonborns.""",
            img_url="https://i.imgur.com/3id7deT.jpg",
            faith="Bahamut, the Platinum Dragon"
        ),
            Character(
            user_id=None,
            level=5,
            name="Zara",
            role="Cleric",
            race="Drow",
            max_hp=42,
            current_hp=42,
            strength=10,
            dexterity=18,
            constitution=14,
            intelligence=12,
            wisdom=16,
            charisma=14,
            armor=["Chain Mail"],
            equipped=["Mace", "Shield"],
            inventory=["Healing Potion", "Holy Symbol", "Spider Silk"],
            languages=["Common", "Elvish", "Undercommon"],
            spells=["Cure Wounds", "Bane", "Inflict Wounds"],
            tools=[],
            weapons=["Mace"],
            initiative=4,
            armor_class=16,
            vision='superior darkvision',
            acrobatics=4,
            animal_handling=3,
            arcana=1,
            athletics=1,
            deception=3,
            history=1,
            insight=3,
            intimidation=2,
            investigation=1,
            medicine=3,
            nature=1,
            perception=3,
            performance=2,
            persuasion=2,
            religion=3,
            sleight_of_hand=4,
            stealth=4,
            survival=1,
            alignment="Neutral Evil",
            appearance="""Zara is a striking Drow with
                           obsidian skin and silver hair cascading
                           down her back. Her lavender eyes gleam
                           with a malevolent glint, betraying her
                           malicious nature. Clad in dark robes
                           adorned with spider motifs, she moves
                           gracefully, like a shadow lurking in
                           darkness. Her voice is soft, yet filled
                           with eerie charm, capable of captivating
                           and manipulating those around her.""",
            background="""Born into the heart of a sinister Drow
                           society, Zara grew up under
                           the rule of the evil goddess Lolth. As
                           a devoted priestess of Lolth, she was
                           taught the ways of deception, cruelty,
                           and dark magic. Embracing the teachings
                           of her goddess, Zara became skilled in
                           manipulation, using her charm and
                           enchantments to bend others to her will.
                           She mastered the art of dark magic,
                           channeling divine power from Lolth to
                           inflict pain and suffering upon her
                           enemies. Zara's loyalty to Lolth is
                           unwavering, and she seeks to advance
                           her position within the Drow society,
                           aiming to become a high priestess and
                           earn the favor of her goddess. With her
                           mace in hand and her spells at her
                           disposal, Zara seeks to further the
                           goals of Lolth, spreading chaos and
                           treachery wherever she goes.""",
            img_url="https://i.imgur.com/Pk86mKN.jpg",
            faith="Lolth, the Evil Goddess of Spiders and Deceit"
        ),
    ]
    for character in characters:
        db.session.add(character)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_users():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.characters RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM characters"))

    db.session.commit()
